package main

import (
	"context"
	"fmt"

	"github.com/google/go-github/v67/github"
	"golang.org/x/oauth2"
)

func newGitHubClient(ctx context.Context, token string) *github.Client {
	ts := oauth2.StaticTokenSource(&oauth2.Token{AccessToken: token})
	tc := oauth2.NewClient(ctx, ts)
	return github.NewClient(tc)
}

// CreatePR creates a pull request for the given feature branch and returns the PR number.
// The body automatically includes "Closes #{issueNumber}" for GitHub auto-linking.
func CreatePR(ctx context.Context, client *github.Client, owner, repo string, issueNumber int, title, head, base string) (int, error) {
	body := fmt.Sprintf("Closes #%d\n\nThis PR was automatically generated by the AI agent.", issueNumber)
	pr, _, err := client.PullRequests.Create(ctx, owner, repo, &github.NewPullRequest{
		Title: github.String(title),
		Body:  github.String(body),
		Head:  github.String(head),
		Base:  github.String(base),
	})
	if err != nil {
		return 0, fmt.Errorf("CreatePR: %w", err)
	}
	return pr.GetNumber(), nil
}

// PostIssueComment posts a comment on the given GitHub issue.
func PostIssueComment(ctx context.Context, client *github.Client, owner, repo string, issueNumber int, body string) error {
	_, _, err := client.Issues.CreateComment(ctx, owner, repo, issueNumber, &github.IssueComment{
		Body: new(body),
	})
	if err != nil {
		return fmt.Errorf("PostIssueComment: %w", err)
	}
	return nil
}
